logging:
  level:
    root: INFO

kafka:
  bootstrap-servers: localhost:9092

topic:
  receiver: receiver.t

spring:
  cloud:
    stream:
      bindings:
        input:
          consumer:
            header-mode: raw